version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Email:1:1,EmailRetry:1:1,EmailFail:1:1"

  email-service:
    image: com/webtrekk/email-service
    container_name: email-service
    build: .
    ports:
      - 8888:8888
    depends_on:
      - kafka
      - zookeeper
    links:
      - kafka:kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092